production:
  domain:
  - name: "bricksco@bricksites.com"
    ssh_options:
    - "-p 2222"
  deploy_to: "~/public_html/christianity/"
  repository: "git@github.com:micahredding/christianity-against-religion.git"
  branch: "master"